/**
 * Types for the scroll-driven first-person flythrough of the 3D masterplan.
 *
 * World units match plots-3d.json (the site spans roughly x -24..35, z -20..24).
 * Driving paths are generated by scripts/flythrough/build_route.py, which A*s
 * through the gaps between plots so the camera follows roads rather than
 * cutting across lots.
 */

export interface FlythroughStation {
  id: string
  /** Shown in the progress rail. */
  label: string
  /** Amenity `name` in plots-3d.json — supplies the clip for this stop. */
  amenity?: string
  /**
   * Driving path to this station as [x, z] world points, road-following.
   * Two or more points build a spline the camera travels along.
   */
  points?: Array<[number, number]>
  /**
   * Straight runs of this leg as [u0, u1] arc-length fractions. While the
   * camera is inside one, the road footage replaces the 3D drive.
   */
  straights?: Array<[number, number]>
  /** What the camera turns to face once it arrives. */
  target?: [number, number]
  /** Explicit standpoint for stations with no driving path (entry, aerial). */
  at?: [number, number]
  /** Explicit aim point, overriding the look-ahead along the path. */
  lookAt?: [number, number]
  /** Height of the aim point, for explicit poses. */
  lookHeight?: number
  /** Camera eye height. ~1.75 reads as standing. */
  eye: number
  /** Vertical field of view. Narrower = longer lens = more compression. */
  fov?: number
  /** Scroll length of the travel leg into this station. */
  duration: number
  ease?: string
  /** Scroll held at the station — this is what scrubs the clip. */
  dwell?: number
  /** Take the whole screen with the amenity clip on arrival. */
  fullscreenVideo?: boolean
  /**
   * A clip that belongs to this stop rather than to an amenity, relative to
   * the project asset root. Must be an all-intra encode: the dwell scrubs it.
   * Wins over the amenity clip, loses to a panorama.
   */
  video?: string
  /**
   * Equirectangular 360 for this stop, relative to the project asset root.
   * Takes precedence over the clip: a real photographic sphere the visitor
   * can look around beats a video pan of the same room.
   */
  panorama?: string
  /** Degrees of yaw swept across the dwell. */
  panoSweep?: number
  /** Yaw the sweep starts from, in degrees. */
  panoStart?: number
  title?: string
  description?: string
  /** Terminal station — reaching it offers the handoff into the explorer. */
  isExit?: boolean
}

export interface FlythroughConfig {
  /** Scroll distance, in viewport heights, per unit of station duration. */
  scrollPerUnit?: number
  /**
   * How far ahead along the path the camera aims, as a fraction of the leg.
   * Larger looks further down the road and feels calmer through corners.
   */
  lookAhead?: number
  /**
   * All-intra clip of a straight forward dolly, scrubbed across each leg's
   * `straights`. Relative to the project asset root.
   */
  roadVideo?: string
  stations: FlythroughStation[]
}

/** Live camera state mutated in place by the GSAP timeline. */
export interface FlyCam {
  px: number
  py: number
  pz: number
  tx: number
  ty: number
  tz: number
  fov: number
}
